import { PrismaClient } from "@prisma/client";
const prisma = new PrismaClient();

const REVIEWS: Record<string, string> = {
  "kitchen":    "We were happy to find that the kitchen had complete cooking equipment. Everything was in great condition and made our stay so much more enjoyable.",
  "second":     "This was our second time staying here and it was just as lovely as the first. Consistent quality and service!",
  "advertised": "Everything was exactly as advertised and the pictures did not disappoint. A truly wonderful place to stay.",
  "better":     "The property was even better in person — modern, spotless, and incredibly comfortable.",
  "peaceful":   "We were impressed by how peaceful the neighborhood was. Perfect for a relaxing getaway.",
  "minimalist": "Loved the minimalist setup and eco-friendly touches throughout the unit. A refreshing and thoughtful stay.",
  "home":       "I felt right at home here. There's something very calming about the space — clean, quiet, and well-designed.",
  "aircon":     "The air conditioning was a blessing during our stay, and the unit was kept spotlessly clean throughout.",
  "cleanest":   "I travel a lot, and this was by far one of the cleanest Airbnb units I've ever stayed in. Will definitely return.",
  "recommend":  "Highly recommend this place for anyone who wants a quiet and comfortable stay near the city.",
  "melody":     "Host Melody went above and beyond to accommodate our needs. Truly exceptional hospitality!",
  "cozy":       "The space had a very cozy and warm vibe; everything was clean and well-maintained. Felt like home instantly.",
  "convenient": "Very convenient location with easy access to shops and restaurants. Ideal for both leisure and business travel.",
  "secure":     "Felt very secure in the gated subdivision, and the caretaker was always available when we needed assistance.",
  "retreat":    "Our stay felt like a true retreat — away from the hustle, yet close to everything we needed.",
  "detail":     "We appreciated the attention to detail — from the cozy linens to the well-stocked kitchen. Highly recommended!",
  "host":       "Melody was an exceptional host — she responded quickly to all our messages and made check-in seamless.",
  "bathroom":   "Clean bathroom, fresh towels, and a great water pressure — the small things that make a big difference!",
  "kids":       "My kids enjoyed the open living space, and we all slept comfortably. A great family-friendly unit!",
  "essentials": "The house was immaculately clean and had all the essentials we needed. Stress-free from check-in to check-out.",
};

const data: { name: string; location: string; rating: number; message: string }[] = [
  { name: "Ashley W.",   location: "Naga",           rating: 5, message: REVIEWS["kitchen"] },
  { name: "Robert A.",   location: "Legazpi",         rating: 5, message: REVIEWS["second"] },
  { name: "Sarah N.",    location: "Parañaque",        rating: 5, message: REVIEWS["advertised"] },
  { name: "Grace L.",    location: "Olongapo",         rating: 5, message: REVIEWS["better"] },
  { name: "Jose E.",     location: "Valenzuela",       rating: 5, message: REVIEWS["peaceful"] },
  { name: "Juan U.",     location: "San Pedro",        rating: 5, message: REVIEWS["second"] },
  { name: "John G.",     location: "Pasig",            rating: 5, message: REVIEWS["minimalist"] },
  { name: "Liza K.",     location: "Batangas City",    rating: 5, message: REVIEWS["second"] },
  { name: "Antonio N.",  location: "San Fernando",     rating: 5, message: REVIEWS["home"] },
  { name: "Robert H.",   location: "Tuguegarao",       rating: 5, message: REVIEWS["aircon"] },
  { name: "David I.",    location: "Sorsogon",         rating: 5, message: REVIEWS["aircon"] },
  { name: "Jessica R.",  location: "San Pedro",        rating: 5, message: REVIEWS["cleanest"] },
  { name: "Antonio X.",  location: "Ilagan",           rating: 5, message: REVIEWS["recommend"] },
  { name: "Jessica V.",  location: "Manila",           rating: 5, message: REVIEWS["recommend"] },
  { name: "Pedro O.",    location: "Parañaque",        rating: 5, message: REVIEWS["melody"] },
  { name: "Amanda D.",   location: "Valenzuela",       rating: 5, message: REVIEWS["cleanest"] },
  { name: "Sarah K.",    location: "Sorsogon",         rating: 5, message: REVIEWS["cozy"] },
  { name: "John M.",     location: "Puerto Princesa",  rating: 5, message: REVIEWS["convenient"] },
  { name: "Robert P.",   location: "Cainta",           rating: 5, message: REVIEWS["convenient"] },
  { name: "Jessica M.",  location: "Angono",           rating: 5, message: REVIEWS["secure"] },
  { name: "Jose G.",     location: "San Pedro",        rating: 5, message: REVIEWS["second"] },
  { name: "Emily S.",    location: "Caloocan",         rating: 5, message: REVIEWS["retreat"] },
  { name: "Grace Q.",    location: "Legazpi",          rating: 5, message: REVIEWS["retreat"] },
  { name: "Carlos C.",   location: "Antipolo",         rating: 5, message: REVIEWS["melody"] },
  { name: "Ashley Y.",   location: "Caloocan",         rating: 5, message: REVIEWS["essentials"] },
  { name: "Amanda R.",   location: "Quezon City",      rating: 5, message: REVIEWS["detail"] },
  { name: "John I.",     location: "Santa Rosa",       rating: 5, message: REVIEWS["peaceful"] },
  { name: "James R.",    location: "San Pedro",        rating: 5, message: REVIEWS["convenient"] },
  { name: "Rica Q.",     location: "Malabon",          rating: 5, message: REVIEWS["peaceful"] },
  { name: "Michael X.",  location: "Lipa",             rating: 5, message: REVIEWS["advertised"] },
  { name: "Michael I.",  location: "Los Baños",        rating: 5, message: REVIEWS["peaceful"] },
  { name: "Grace E.",    location: "Valenzuela",       rating: 5, message: REVIEWS["convenient"] },
  { name: "John H.",     location: "Olongapo",         rating: 5, message: REVIEWS["convenient"] },
  { name: "Carlos K.",   location: "Santa Rosa",       rating: 5, message: REVIEWS["advertised"] },
  { name: "Amanda Z.",   location: "Valenzuela",       rating: 5, message: REVIEWS["second"] },
  { name: "Liza P.",     location: "Taguig",           rating: 5, message: REVIEWS["secure"] },
  { name: "Rica R.",     location: "Ilagan",           rating: 5, message: REVIEWS["cozy"] },
  { name: "Ana B.",      location: "Caloocan",         rating: 5, message: REVIEWS["host"] },
  { name: "Liza F.",     location: "Ilagan",           rating: 5, message: REVIEWS["secure"] },
  { name: "Jessica P.",  location: "Quezon City",      rating: 5, message: REVIEWS["kitchen"] },
  { name: "Rica F.",     location: "Dagupan",          rating: 5, message: REVIEWS["better"] },
  { name: "Liza D.",     location: "Valenzuela",       rating: 5, message: REVIEWS["convenient"] },
  { name: "Michael J.",  location: "Taytay",           rating: 5, message: REVIEWS["kitchen"] },
  { name: "Maria F.",    location: "Ilagan",           rating: 5, message: REVIEWS["home"] },
  { name: "Liza A.",     location: "Ilagan",           rating: 5, message: REVIEWS["bathroom"] },
  { name: "Ashley P.",   location: "Parañaque",        rating: 5, message: REVIEWS["cozy"] },
  { name: "Jessica Q.",  location: "Ilagan",           rating: 5, message: REVIEWS["kids"] },
  { name: "Rica I.",     location: "Pagbilao",         rating: 5, message: REVIEWS["secure"] },
  { name: "James B.",    location: "Baguio",           rating: 5, message: REVIEWS["essentials"] },
  { name: "David D.",    location: "Batangas City",    rating: 5, message: REVIEWS["detail"] },
  { name: "Pedro G.",    location: "Pasig",            rating: 5, message: REVIEWS["minimalist"] },
  { name: "Emily R.",    location: "Tuguegarao",       rating: 5, message: REVIEWS["kitchen"] },
  { name: "Ana L.",      location: "Parañaque",        rating: 5, message: REVIEWS["essentials"] },
  { name: "Grace F.",    location: "Batangas City",    rating: 5, message: REVIEWS["bathroom"] },
  { name: "Carlos M.",   location: "Ilagan",           rating: 5, message: REVIEWS["secure"] },
  { name: "Jose S.",     location: "Quezon City",      rating: 5, message: REVIEWS["melody"] },
  { name: "Emily O.",    location: "Pagbilao",         rating: 5, message: REVIEWS["home"] },
  { name: "Robert J.",   location: "Angeles",          rating: 5, message: REVIEWS["essentials"] },
  { name: "Emily D.",    location: "Taguig",           rating: 5, message: REVIEWS["advertised"] },
  { name: "David P.",    location: "Ilagan",           rating: 5, message: REVIEWS["kids"] },
  { name: "Michael N.",  location: "Angono",           rating: 5, message: REVIEWS["host"] },
  { name: "Maria S.",    location: "Manila",           rating: 5, message: REVIEWS["cozy"] },
  { name: "Pedro H.",    location: "Ilagan",           rating: 5, message: REVIEWS["kitchen"] },
  { name: "Pedro K.",    location: "Lipa",             rating: 5, message: REVIEWS["secure"] },
  { name: "Maria Z.",    location: "Calamba",          rating: 5, message: REVIEWS["cozy"] },
  { name: "David C.",    location: "Taytay",           rating: 5, message: REVIEWS["cleanest"] },
  { name: "Ashley V.",   location: "Naga",             rating: 5, message: REVIEWS["home"] },
  { name: "Ana X.",      location: "Parañaque",        rating: 5, message: REVIEWS["secure"] },
  { name: "Ana G.",      location: "Clark",            rating: 5, message: REVIEWS["second"] },
  { name: "Maria U.",    location: "Malabon",          rating: 5, message: REVIEWS["home"] },
  { name: "Carlos Z.",   location: "San Fernando",     rating: 5, message: REVIEWS["retreat"] },
  { name: "Maria D.",    location: "Olongapo",         rating: 5, message: REVIEWS["minimalist"] },
  { name: "Rica M.",     location: "Valenzuela",       rating: 5, message: REVIEWS["minimalist"] },
  { name: "Juan U.",     location: "Malabon",          rating: 5, message: REVIEWS["secure"] },
  { name: "Amanda F.",   location: "Malabon",          rating: 5, message: REVIEWS["essentials"] },
  { name: "James B.",    location: "Ilagan",           rating: 5, message: REVIEWS["retreat"] },
  { name: "Michael U.",  location: "Sorsogon",         rating: 5, message: REVIEWS["melody"] },
  { name: "Antonio F.",  location: "Parañaque",        rating: 5, message: REVIEWS["host"] },
  { name: "Robert P.",   location: "Pagbilao",         rating: 5, message: REVIEWS["second"] },
  { name: "Pedro L.",    location: "Clark",            rating: 5, message: REVIEWS["cleanest"] },
  { name: "John Y.",     location: "Tanauan",          rating: 5, message: REVIEWS["cozy"] },
  { name: "Grace R.",    location: "Tuguegarao",       rating: 5, message: REVIEWS["retreat"] },
  { name: "Sarah F.",    location: "Baguio",           rating: 5, message: REVIEWS["retreat"] },
  { name: "Amanda A.",   location: "Caloocan",         rating: 5, message: REVIEWS["bathroom"] },
  { name: "Sarah U.",    location: "Manila",           rating: 5, message: REVIEWS["kitchen"] },
  { name: "David F.",    location: "Dagupan",          rating: 5, message: REVIEWS["retreat"] },
  { name: "Juan N.",     location: "Biñan",            rating: 5, message: REVIEWS["second"] },
  { name: "James C.",    location: "Tuguegarao",       rating: 5, message: REVIEWS["essentials"] },
  { name: "Antonio F.",  location: "Caloocan",         rating: 5, message: REVIEWS["detail"] },
  { name: "Jose X.",     location: "Clark",            rating: 5, message: REVIEWS["kitchen"] },
  { name: "Juan L.",     location: "Naga",             rating: 5, message: REVIEWS["retreat"] },
  { name: "James U.",    location: "Legazpi",          rating: 5, message: REVIEWS["retreat"] },
  { name: "Jose I.",     location: "Makati",           rating: 5, message: REVIEWS["cleanest"] },
  { name: "Ashley K.",   location: "Los Baños",        rating: 5, message: REVIEWS["cozy"] },
  { name: "Ana T.",      location: "Biñan",            rating: 5, message: REVIEWS["melody"] },
  { name: "Sarah R.",    location: "San Fernando",     rating: 5, message: REVIEWS["better"] },
  { name: "Juan O.",     location: "Tuguegarao",       rating: 5, message: REVIEWS["detail"] },
  { name: "Carlos C.",   location: "Cainta",           rating: 5, message: REVIEWS["peaceful"] },
];

async function main() {
  console.log(`Inserting ${data.length} testimonials for property ID=1...`);
  const result = await prisma.testimonial.createMany({
    data: data.map((t) => ({ ...t, propertyId: 1, isActive: true })),
  });
  console.log(`Done! Inserted ${result.count} records.`);
}

main()
  .catch((e) => { console.error(e); process.exit(1); })
  .finally(() => prisma.$disconnect());
