#!/usr/bin/env node
/**
 * Generates SHA-256 hashes for payment QR code images.
 * Run: npm run qr:hash
 *
 * Outputs the hashes and writes them to .env.local so the frontend
 * can verify QR integrity at runtime via the Web Crypto API.
 */

const fs = require("fs");
const path = require("path");
const crypto = require("crypto");

const QR_FILES = {
  NEXT_PUBLIC_QR_HASH_GCASH: "public/qr/gcash.jpg",
  NEXT_PUBLIC_QR_HASH_BPI: "public/qr/bpi.png",
};

const envPath = path.resolve(__dirname, "..", ".env.local");

// Read existing .env.local (preserve other vars)
let existing = "";
if (fs.existsSync(envPath)) {
  existing = fs.readFileSync(envPath, "utf-8");
}

const hashes = {};

for (const [envKey, filePath] of Object.entries(QR_FILES)) {
  const abs = path.resolve(__dirname, "..", filePath);
  if (!fs.existsSync(abs)) {
    console.error(`[ERROR] QR image not found: ${filePath}`);
    process.exit(1);
  }
  const buf = fs.readFileSync(abs);
  const hash = "sha256-" + crypto.createHash("sha256").update(buf).digest("base64");
  hashes[envKey] = hash;
  console.log(`${envKey}=${hash}`);
}

// Update .env.local — replace existing lines or append
let lines = existing.split("\n");
for (const [key, value] of Object.entries(hashes)) {
  const idx = lines.findIndex((l) => l.startsWith(`${key}=`));
  const entry = `${key}="${value}"`;
  if (idx !== -1) {
    lines[idx] = entry;
  } else {
    // Add under a QR section header if not already present
    if (!lines.some((l) => l.includes("# QR Integrity"))) {
      lines.push("", "# QR Integrity (generated by scripts/generate-qr-hash.js)");
    }
    lines.push(entry);
  }
}

fs.writeFileSync(envPath, lines.join("\n"));
console.log(`\n✅ Hashes written to .env.local`);
